# Generated by Django 5.2.5 on 2025-09-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view books'), ('can_create', 'Can create a new book'), ('can_edit', 'Can edit book details'), ('can_delete', 'Can delete a book')]},
        ),
    ]
