# Generated by Django 5.2.7 on 2025-10-17 00:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='message_body',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_planned_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_root_cause_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL, verbose_name='Creating Engineer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='notifications_received', to='notifications_app.customer'),
        ),
    ]
