# Generated by Django 5.2.5 on 2025-10-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications_app', '0002_rename_message_notification_message_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': 'Engineer', 'verbose_name_plural': 'Engineers'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready to Send'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', help_text='Current status of the notification message.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_type',
            field=models.CharField(choices=[('FIBER', 'Fiber Optic'), ('CABLE', 'Cable Internet'), ('DSL', 'DSL'), ('FIXED', 'Fixed Wireless')], default='FIBER', max_length=100),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this engineer belongs to. An engineer will get all permissions granted to each of their groups.', related_name='engineer_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this engineer.', related_name='engineer_permissions', to='auth.permission'),
        ),
    ]
